accounts/urls.py
from django.urls import path
from .views import SignupView
from django.contrib.auth.views import *
from accounts.views import *

app_name = "accounts"

signup_view = SignupView.as_view(template_name='accounts/signup.html')
login_view = CustomLoginView.as_view()
logout_view = LogoutView.as_view(
    template_name='accounts/logout.html', redirect_field_name='top')
password_change_view = PasswordChangeView.as_view(
    template_name='accounts/password_change.html')
password_change_done_view = PasswordChangeDoneView.as_view(
    template_name='accounts/password_change_done.html')
password_reset_view = PasswordResetView.as_view(
    template_name='accounts/password_reset.html')
password_reset_done_view = PasswordResetDoneView.as_view(
    template_name='accounts/password_reset_done.html')
password_reset_confirm_view = PasswordResetConfirmView.as_view(
    template_name='accounts/password_reset_confirm.html')
password_reset_complete_view = PasswordResetCompleteView.as_view(
    template_name='accounts/password_reset_complete.html')

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('password_change/', password_change_view, name='password_change'),
    path('password_change/done/', password_change_done_view,
         name='password_change_done'),
    path('password_reset/', password_reset_view, name='password_reset'),
    path('password_reset/done/', password_reset_done_view,
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', password_reset_confirm_view,
         name='password_reset_confirm'),
    path('reset/done/', password_reset_complete_view,
         name='password_reset_complete'),
    path('signup_success/', signup_success, name='signup_success'),
    path('signup/', signup_view, name='signup'),

    path('profile/', profile_view, name='profile_view'),
    path('edit_profile/', edit_profile_view, name='edit_profile_view')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from general.views import top

urlpatterns = [
    path('', top, name='top'),
    path('admin/', admin.site.urls),
    path('topics/', include('topics.urls')),
    path('general/', include('general.urls')),
    path('accounts/', include('accounts.urls')),
    path('ranking/', include('ranking.urls')),
]

templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <title>CivicSeek</title>
    {% bootstrap_css %}
    {% block extraheader %}

    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a href="/" class="navbar-brand">CivicSeek</a>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{% url 'home' %}" class="nav-link text-primary">HOME</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'accounts:logout' %}" class="nav-link">ログアウト</a>
            </li>
            <li>
              <a href="{% url 'accounts:profile_view' %}" class="nav-link">プロフィール</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'accounts:login' %}" class="nav-link">ログイン</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'accounts:signup' %}" class="nav-link">サインアップ</a>
            </li>
          {% endif %}
          <li>
            <a href="{% url 'show_ranking' %}" class="nav-link">ランキング</a>
          </li>
        </ul>
      </div>
    </nav>
    <main>
      <div class="container mt-4">
        {% bootstrap_messages %}
        {% block main %}

        {% endblock %}
      </div>
    </main>
    <footer>
      {% block extrafooter %}

      {% endblock %}
    </footer>
    {% bootstrap_javascript %}
  </body>
</html>